### PR TITLE
Add date in Main/Admin

### PR DESCRIPTION
**Pull request by Florentin-bron**
Adding date with format **Hour : Minute** on the right of each card in Main/Admin

### CODE REVIEW

**Comment by kongr45gpen** [comment]
Thanks for the update! It works exactly as expected.

I have one little request: The date currently goes below the text, even if there is enough space for it to go above, and this creates a lot of unused white space. Maybe integrating into the `question__vote` div above will solve this issue.

Screenshot_20211104_152125

**Comment by Florentin-bron** [comment]
Ok i will fix it when i can.
I didnt spot it yesterday but yeah it create a lot of spaces for nothing and surely moving it to the div `question__vote` should fix that.

**Comment by Florentin-bron** [comment]
Should i move the div with the heart in the div with the text ? It will be at the same spot but without the margin and clean a lot of spaces ?
Current :
image

With the heart div moved in the text div:
image

**Comment by kongr45gpen** [comment]
Hmm, when moved to the test div I still see there is some white space below. Maybe playing with a negative `margin-bottom` will help to clear it?

Also, I would suggest trying on a question with a _Response_, since the `float`s might break the layout entirely.

**Comment by Florentin-bron** [comment]
I fix the spaces now and the response didn't broke it at all
image

**Comment by kongr45gpen** [comment]
Sorry for the delay, but this looks great! Thank you again for the initiative.

**Comment by Florentin-bron** [comment]
Thank you for merging my work ! Happy to see that this dev was useful !

**Pull request merged**
